### ISSUE TITLE
Upload to the extensions website!

### ISSUE THREAD

**Issue by Hedronmx** [filipizydorczyk/wireless-hid-reloaded#1]
This fork really rocks! Please upload to the extension site!

**Comment by filipizydorczyk** [comment]
Hello! Thanks for sugestion and sorry for late response I didnt expect anyone to event find my account xD
Honestly I am not even actively maintaining this project. Whenever updates comes out I just move supported version up and if extension brakes I am looking up to https://github.com/vchlum/wireless-hid for fixes. This is original extension that I just added some things on top of.
I started this project because I just wanted something that original app didnt have and I am not very familiar with gnome stack and libraries therefore I dont wnat to upload this extension on gnome site. I just dont want to do mess with extension that I am not sure if it works as expected and depending with updates on original repo. If you want you can download original one from here: https://extensions.gnome.org/extension/4228/wireless-hid/ or install this one from instructions in readme. If you run 

```
scripts/release.sh && scripts/install.sh
```

and restart your gnome shell, extension should be working :D

Thanks once again for a comment
